/*
    Yojimbo Client/Server Network Library.

    Copyright © 2016 - 2026, Más Bandwidth LLC.

    Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

        1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

        2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer
           in the documentation and/or other materials provided with the distribution.

        3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived
           from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
    SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
    SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
    WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
    USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/*
    TypeScript port of include/yojimbo_message.h + source/yojimbo_message.cpp (yojimbo 1.13.5).

    API idioms:

      - Messages: derive from Message (or BlockMessage) and implement Serialize( stream ) once with the slot based
        serialize_* functions; it serves read, write and measure (upstream's template + YOJIMBO_VIRTUAL_SERIALIZE_FUNCTIONS):

            class TestMessage extends Message
            {
                sequence = 0;
                Serialize( stream: BaseStream ): boolean
                {
                    return serialize_bits( stream, this, 'sequence', 16 );
                }
            }

      - Message factories: YOJIMBO_MESSAGE_FACTORY( numTypes, [ [ type, MessageClass ], ... ] ) returns a MessageFactory
        subclass (the YOJIMBO_MESSAGE_FACTORY_START / YOJIMBO_DECLARE_MESSAGE_TYPE / YOJIMBO_MESSAGE_FACTORY_FINISH macros):

            const TestMessageFactory = YOJIMBO_MESSAGE_FACTORY( NUM_TEST_MESSAGE_TYPES, [
                [ TEST_MESSAGE, TestMessage ],
                [ TEST_BLOCK_MESSAGE, TestBlockMessage ],
            ] );
            const factory = new TestMessageFactory( allocator );

        Each message is created with YOJIMBO_NEW on the factory's allocator, so creation fails (null) when the allocator
        does. Deriving from MessageFactory and overriding CreateMessageInternal works as upstream too.

      - Reference counting is upstream's contract: CreateMessage returns a message with one reference; SendMessage
        transfers it; ReceiveMessage hands one to you, which you return with ReleaseMessage. When the count reaches zero
        the factory destroys the message (Dispose, then its block is freed). Message leak tracking (on by default)
        reports and asserts on unreleased messages when the factory is disposed.

      - Blocks: allocate the block from the allocator (YOJIMBO_ALLOCATE( factory.GetAllocator(), size ) or the
        client/server AllocateBlock) and attach it with AttachBlock( allocator, blockData, blockSize ). The message owns
        it from then on and frees it with that allocator when it is destroyed. DetachBlock hands ownership back.
*/

import { BaseStream, serialize_int, serialize_bytes } from '../serialize/serialize.ts';
import { Serializable } from '../include/yojimbo_serialize.ts';
import { Allocator, YOJIMBO_ALLOCATE, YOJIMBO_FREE, YOJIMBO_NEW, YOJIMBO_DELETE } from './yojimbo_allocator.ts';
import { YOJIMBO_DEBUG_MESSAGE_LEAKS } from './yojimbo_config.ts';
import { yojimbo_assert, yojimbo_printf, YOJIMBO_LOG_LEVEL_ERROR } from './yojimbo_platform.ts';

/**
    A reference counted object that can be serialized to a bitstream.

    Messages are objects that are sent between client and server across the connection. They are carried inside the ConnectionPacket generated by the Connection class. Messages can be sent reliable-ordered, or unreliable-unordered, depending on the configuration of the channel they are sent over.

    To use messages, create your own set of message classes by inheriting from this class (or from BlockMessage, if you want to attach data blocks to your message), then setup your message types and a message factory to create your message instances by type.

    @see BlockMessage
    @see MessageFactory
    @see Connection
 */

export abstract class Message extends Serializable
{
    private m_refCount: number;                 ///< Number of references on this message object. Starts at 1. Message is destroyed when it reaches 0.
    private m_id: number;                       ///< The message id (uint16). For messages sent over reliable-ordered channels, this starts at 0 and increases with each message sent. For unreliable-unordered channels this is set to the sequence number of the packet the message was included in.
    private m_type: number;                     ///< The message type (15 bits). Corresponds to the type integer used when the message was created though the message factory.
    private m_blockMessage: boolean;            ///< True if this is a block message. If true then the message is a BlockMessage. Lightweight RTTI.

    /**
        Message constructor.
        Don't call this directly, use a message factory instead.
        @param blockMessage True if this is a block message.
        @see MessageFactory::CreateMessage
     */

    constructor( blockMessage: boolean = false )
    {
        super();
        this.m_refCount = 1;
        this.m_id = 0;
        this.m_type = 0;
        this.m_blockMessage = blockMessage;
    }

    /**
        Set the message id.
        When messages are sent over a reliable-ordered channel, the message id starts at 0 and increases with each message sent over that channel.
        When messages are sent over an unreliable-unordered channel, the message id is set to the sequence number of the packet it was delivered in.
        @param id The message id (uint16).
     */

    SetId( id: number ): void
    {
        this.m_id = id & 0xFFFF;
    }

    /**
        Get the message id.
        @returns The message id.
     */

    GetId(): number
    {
        return this.m_id;
    }

    /**
        Get the message type.
        This corresponds to the type value used to create the message in the message factory.
        @returns The message type.
     */

    GetType(): number
    {
        return this.m_type;
    }

    /**
        Get the reference count on the message.
        Messages start with a reference count of 1 when they are created. This is decreased when they are released.
        When the reference count reaches 0, the message is destroyed.
        @returns The reference count on the message.
     */

    GetRefCount(): number
    {
        return this.m_refCount;
    }

    /**
        Is this a block message?
        Block messages are of type BlockMessage and can have a data block attached to the message.
        @returns True if this is a block message, false otherwise.
     */

    IsBlockMessage(): boolean
    {
        return this.m_blockMessage;
    }

    /**
        Set the message type. Called by the message factory after it creates a message.
        Internal (protected upstream, MessageFactory is a friend).
     */

    SetType( type: number ): void
    {
        this.m_type = type & 0x7FFF;
    }

    /**
        Add a reference to the message. Internal: use MessageFactory::AcquireMessage.
     */

    Acquire(): void
    {
        yojimbo_assert( this.m_refCount > 0, "m_refCount > 0", "Message::Acquire" );
        this.m_refCount++;
    }

    /**
        Remove a reference from the message. Internal: use MessageFactory::ReleaseMessage.
     */

    Release(): void
    {
        yojimbo_assert( this.m_refCount > 0, "m_refCount > 0", "Message::Release" );
        this.m_refCount--;
    }

    /**
        Message destructor, run by the message factory when the last reference is released. Never call it directly.
        @see MessageFactory::ReleaseMessage
     */

    Dispose(): void
    {
        yojimbo_assert( this.m_refCount === 0, "m_refCount == 0", "Message::~Message" );
    }
}

/**
    A message which can have a block of data attached to it.
    @see ChannelConfig
 */

export class BlockMessage extends Message
{
    private m_allocator: Allocator | null;          ///< Allocator for the block attached to the message. null if no block is attached.
    private m_blockData: Uint8Array | null;         ///< The block data. null if no block is attached.
    private m_blockSize: number;                    ///< The block size (bytes). 0 if no block is attached.

    /**
        Block message constructor.
        Don't call this directly, use a message factory instead.
     */

    constructor()
    {
        super( true );
        this.m_allocator = null;
        this.m_blockData = null;
        this.m_blockSize = 0;
    }

    /**
        Attach a block to this message.
        You can only attach one block. This method will assert if a block is already attached.
        The block must have been allocated from `allocator`; the message frees it with that allocator.
        @see Client::AttachBlockToMessage
        @see Server::AttachBlockToMessage
     */

    AttachBlock( allocator: Allocator, blockData: Uint8Array, blockSize: number ): void
    {
        yojimbo_assert( blockData, "blockData", "BlockMessage::AttachBlock" );
        yojimbo_assert( blockSize > 0, "blockSize > 0", "BlockMessage::AttachBlock" );
        yojimbo_assert( !this.m_blockData, "!m_blockData", "BlockMessage::AttachBlock" );
        this.m_allocator = allocator;
        this.m_blockData = blockData;
        this.m_blockSize = blockSize;
    }

    /**
        Detach the block from this message.
        By doing this you are responsible for keeping the block and allocator and making sure the block is freed.
        @see Client::DetachBlockFromMessage
        @see Server::DetachBlockFromMessage
     */

    DetachBlock(): void
    {
        this.m_allocator = null;
        this.m_blockData = null;
        this.m_blockSize = 0;
    }

    /**
        Get the allocator used to allocate the block.
        @returns The allocator for the block. null if no block is attached to this message.
     */

    GetAllocator(): Allocator | null
    {
        return this.m_allocator;
    }

    /**
        Get the block data.
        @returns The block data. null if no block is attached.
     */

    GetBlockData(): Uint8Array | null
    {
        return this.m_blockData;
    }

    /**
        Get the size of the block attached to this message.
        @returns The size of the block (bytes). 0 if no block is attached.
     */

    GetBlockSize(): number
    {
        return this.m_blockSize;
    }

    /**
        Serialize function for the block message. Doesn't do anything. The block data is serialized elsewhere.
        You can override the serialize method on a block message to implement your own serialize function. It's just like a regular message with a block attached to it.
     */

    Serialize( _stream: BaseStream ): boolean
    {
        return true;
    }

    /**
        If a block was attached to the message, it is freed here.
     */

    override Dispose(): void
    {
        if ( this.m_allocator )
        {
            this.m_blockData = YOJIMBO_FREE( this.m_allocator, this.m_blockData );
            this.m_blockSize = 0;
            this.m_allocator = null;
        }
        super.Dispose();
    }
}

/**
    Message factory error level.
 */

export const MESSAGE_FACTORY_ERROR_NONE = 0;                                ///< No error. All is well.
export const MESSAGE_FACTORY_ERROR_FAILED_TO_ALLOCATE_MESSAGE = 1;          ///< Failed to allocate a message. Typically this means we ran out of memory on the allocator backing the message factory.

export type MessageFactoryErrorLevel = typeof MESSAGE_FACTORY_ERROR_NONE | typeof MESSAGE_FACTORY_ERROR_FAILED_TO_ALLOCATE_MESSAGE;

/**
    Defines the set of message types that can be created.
    You can derive a message factory yourself to create your own message types, or use YOJIMBO_MESSAGE_FACTORY.
 */

export class MessageFactory
{
    private m_debug: Set<Message> | null;                                   ///< Message leak tracking state, or null when message leak tracking is off.
    private m_allocator: Allocator | null;                                  ///< The allocator used to create messages.
    private m_numTypes: number;                                             ///< The number of message types.
    private m_errorLevel: MessageFactoryErrorLevel;                         ///< The message factory error level.

    /**
        Message factory constructor.
        Pass in the number of message types for the message factory from the derived class.
        @param allocator The allocator used to create messages.
        @param numTypes The number of message types. Valid types are in [0,numTypes-1].
     */

    constructor( allocator: Allocator, numTypes: number )
    {
        this.m_allocator = allocator;
        this.m_numTypes = numTypes;
        this.m_errorLevel = MESSAGE_FACTORY_ERROR_NONE;
        this.m_debug = YOJIMBO_DEBUG_MESSAGE_LEAKS ? new Set<Message>() : null;
    }

    /**
        Message factory destructor.
        Checks for message leaks (on by default): reports and fails through the assert handler on any leaked message.
     */

    Dispose(): void
    {
        yojimbo_assert( this.m_allocator, "m_allocator", "MessageFactory::~MessageFactory" );
        this.m_allocator = null;
        const debug = this.m_debug;
        this.m_debug = null;
        if ( debug && debug.size > 0 )
        {
            yojimbo_printf( YOJIMBO_LOG_LEVEL_ERROR, "you leaked messages!\n" );
            yojimbo_printf( YOJIMBO_LOG_LEVEL_ERROR, "%d messages leaked\n", debug.size );
            for ( const message of debug )
            {
                yojimbo_printf( YOJIMBO_LOG_LEVEL_ERROR, "leaked message %s (type %d, refcount %d)\n", message.constructor.name, message.GetType(), message.GetRefCount() );
            }
            yojimbo_assert( false, "Message leaks detected, see log", "MessageFactory::~MessageFactory" );
        }
    }

    /**
        Create a message by type.
        IMPORTANT: Check the message returned by this call. It can be null if there is no memory to create a message!
        Messages returned from this function have one reference added to them. When you are finished with the message, pass it to MessageFactory::ReleaseMessage.
        @param type The message type in [0,numTypes-1].
        @returns The allocated message, or null if the message could not be allocated. If the message allocation fails, the message factory error level is set to MESSAGE_FACTORY_ERROR_FAILED_TO_ALLOCATE_MESSAGE.
     */

    CreateMessage( type: number ): Message | null
    {
        yojimbo_assert( type >= 0, "type >= 0", "MessageFactory::CreateMessage" );
        yojimbo_assert( type < this.m_numTypes, "type < m_numTypes", "MessageFactory::CreateMessage" );
        const message = this.CreateMessageInternal( type );
        if ( !message )
        {
            this.m_errorLevel = MESSAGE_FACTORY_ERROR_FAILED_TO_ALLOCATE_MESSAGE;
            return null;
        }
        if ( this.m_debug )
            this.m_debug.add( message );
        return message;
    }

    /**
        Add a reference to a message.
        @param message The message to add a reference to.
     */

    AcquireMessage( message: Message | null ): void
    {
        yojimbo_assert( message, "message", "MessageFactory::AcquireMessage" );
        if ( message )
            message.Acquire();
    }

    /**
        Remove a reference from a message.
        Messages have 1 reference when created. When the reference count reaches 0, they are destroyed.
        After releasing you no longer own the message: drop your reference to it.
     */

    ReleaseMessage( message: Message | null ): void
    {
        yojimbo_assert( message, "message", "MessageFactory::ReleaseMessage" );
        if ( !message )
        {
            return;
        }
        message.Release();
        if ( message.GetRefCount() === 0 )
        {
            if ( this.m_debug )
            {
                yojimbo_assert( this.m_debug.has( message ), "message was created by this factory", "MessageFactory::ReleaseMessage" );
                this.m_debug.delete( message );
            }
            yojimbo_assert( this.m_allocator, "m_allocator", "MessageFactory::ReleaseMessage" );
            YOJIMBO_DELETE( this.m_allocator, message );
        }
    }

    /**
        Get the number of message types supported by this message factory.
        @returns The number of message types.
     */

    GetNumTypes(): number
    {
        return this.m_numTypes;
    }

    /**
        Get the allocator used to create messages.
        @returns The allocator.
     */

    GetAllocator(): Allocator
    {
        yojimbo_assert( this.m_allocator, "m_allocator", "MessageFactory::GetAllocator" );
        return this.m_allocator;
    }

    /**
        Get the error level.
        When used with a client or server, an error level on a message factory other than MESSAGE_FACTORY_ERROR_NONE triggers a client disconnect.
     */

    GetErrorLevel(): MessageFactoryErrorLevel
    {
        return this.m_errorLevel;
    }

    /**
        Clear the error level back to no error.
     */

    ClearErrorLevel(): void
    {
        this.m_errorLevel = MESSAGE_FACTORY_ERROR_NONE;
    }

    /** The number of live messages created by this factory (only tracked with message leak tracking on; otherwise 0). */

    GetNumAllocatedMessages(): number
    {
        return this.m_debug ? this.m_debug.size : 0;
    }

    /**
        This method is overridden to create messages by type.
        Create the message with YOJIMBO_NEW on GetAllocator() and set its type with SetMessageType.
        @param type The type of message to be created.
        @returns The message created. Its reference count is 1. null if it could not be created.
     */

    protected CreateMessageInternal( _type: number ): Message | null
    {
        return null;
    }

    /**
        Set the message type of a message.
        @param message The message object.
        @param type The message type to set.
     */

    protected SetMessageType( message: Message, type: number ): void
    {
        message.SetType( type );
    }
}

/** A message class a factory can create: constructed with no arguments. */
export type MessageClass = new () => Message;

/** A message factory class: constructed with the allocator to create messages with. */
export type MessageFactoryClass = new ( allocator: Allocator ) => MessageFactory;

/**
    Define a message factory class (upstream's YOJIMBO_MESSAGE_FACTORY_START, YOJIMBO_DECLARE_MESSAGE_TYPE and
    YOJIMBO_MESSAGE_FACTORY_FINISH macros).
    @param numMessageTypes The number of message types for this factory. Valid types are in [0,numMessageTypes-1].
    @param messageTypes The declared types: [ type, message class ] pairs. Undeclared types create null.
    @param name Optional class name, for debugging.
    @returns The message factory class. Construct it with the allocator: `new TestMessageFactory( allocator )`.
 */

export function YOJIMBO_MESSAGE_FACTORY( numMessageTypes: number, messageTypes: ReadonlyArray<readonly [ number, MessageClass ]>, name: string = "MessageFactory" ): MessageFactoryClass
{
    const table = new Array<MessageClass | undefined>( numMessageTypes ).fill( undefined );
    for ( const [ type, messageClass ] of messageTypes )
    {
        yojimbo_assert( type >= 0 && type < numMessageTypes, "message type in [0,numMessageTypes-1]", "YOJIMBO_DECLARE_MESSAGE_TYPE" );
        table[type] = messageClass;
    }

    const factoryClass = class extends MessageFactory
    {
        constructor( allocator: Allocator )
        {
            super( allocator, numMessageTypes );
        }

        protected override CreateMessageInternal( type: number ): Message | null
        {
            const messageClass = table[type];
            if ( !messageClass )
                return null;
            const message = YOJIMBO_NEW( this.GetAllocator(), () => new messageClass() );
            if ( !message )
                return null;
            this.SetMessageType( message, type );
            return message;
        }
    };

    Object.defineProperty( factoryClass, "name", { value: name } );

    return factoryClass;
}

/** Scratch slot for SerializeMessageBlock (single threaded, never re-entered). */
const block_scratch = { blockSize: 0 };

/**
    Helper function to serialize a block attached to a message. Used by channel implementations.
    Wire format: serialize_int( blockSize, 1, maxBlockSize ) then serialize_bytes( blockData, blockSize ).
    On read the block is allocated from the message factory's allocator and attached to the message.
 */

export function SerializeMessageBlock( stream: BaseStream, messageFactory: MessageFactory, blockMessage: BlockMessage, maxBlockSize: number ): boolean
{
    block_scratch.blockSize = stream.IsWriting ? blockMessage.GetBlockSize() : 0;
    if ( !serialize_int( stream, block_scratch, 'blockSize', 1, maxBlockSize ) )
        return false;
    const blockSize = block_scratch.blockSize;
    let blockData: Uint8Array | null;
    if ( stream.IsReading )
    {
        const allocator = messageFactory.GetAllocator();
        blockData = YOJIMBO_ALLOCATE( allocator, blockSize );
        if ( !blockData )
        {
            yojimbo_printf( YOJIMBO_LOG_LEVEL_ERROR, "error: failed to allocate message block (SerializeMessageBlock)\n" );
            return false;
        }
        blockMessage.AttachBlock( allocator, blockData, blockSize );
    }
    else
    {
        blockData = blockMessage.GetBlockData();
    }
    if ( !serialize_bytes( stream, blockData!, blockSize ) )
        return false;
    return true;
}
