/*
    Yojimbo Client/Server Network Library.

    Copyright © 2016 - 2019, The Network Protocol Company, Inc.

    Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

        1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

        2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer 
           in the documentation and/or other materials provided with the distribution.

        3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived 
           from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
    SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
    SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
    WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
    USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#if DEBUG
#define YOJIMBO_DEBUG_MESSAGE_LEAKS
#endif

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Text;
using System.Threading;

namespace networkprotocol
{
    /**
        A reference counted object that can be serialized to a bitstream.

        Messages are objects that are sent between client and server across the connection. They are carried inside the ConnectionPacket generated by the Connection class. Messages can be sent reliable-ordered, or unreliable-unordered, depending on the configuration of the channel they are sent over.
        
        To use messages, create your own set of message classes by inheriting from this class (or from BlockMessage, if you want to attach data blocks to your message), then setup an enum of all your message types and derive a message factory class to create your message instances by type.
        
        There are macros to help make defining your message factory painless:
        
            YOJIMBO_MESSAGE_FACTORY_START
            YOJIMBO_DECLARE_MESSAGE_TYPE
            YOJIMBO_MESSAGE_FACTORY_FINISH
        
        Once you have a message factory, register it with your declared inside your client and server classes using:
        
            YOJIMBO_MESSAGE_FACTORY
        
        which overrides the Client::CreateMessageFactory and Server::CreateMessageFactory methods so the client and server classes use your message factory type.
        
        See tests/shared.h for an example showing you how to do this, and the functional tests inside tests/test.cpp for examples showing how how to send and receive messages.
        
        @see BlockMessage
        @see MessageFactory
        @see Connection
     */
    public abstract class Message : Serializable
    {
        /**
            Message constructor.
            Don't call this directly, use a message factory instead.
            @param blockMessage 1 if this is a block message, 0 otherwise.
            @see MessageFactory::Create
         */
        public Message(bool blockMessage = false)
        {
            m_refCount = 1;
            m_id = 0;
            m_type = 0;
            m_blockMessage = blockMessage;
        }

        /** 
            Gets or sets the message id.
            When messages are sent over a reliable-ordered channel, the message id starts at 0 and increases with each message sent over that channel.
            When messages are sent over an unreliable-unordered channel, the message id is set to the sequence number of the packet it was delivered in.
            @param id The message id.
         */
        public ushort Id
        {
            get => m_id;
            set => m_id = value;
        }

        /**
            Get the message type.
            This corresponds to the type enum value used to create the message in the message factory.
            @returns The message type.
            @see MessageFactory.
         */
        public int Type
        {
            get => m_type;
            // Called by the message factory after it creates a message.
            protected internal set => m_type = (ushort)value;
        }

        /**
            Get the reference count on the message.
            Messages start with a reference count of 1 when they are created. This is decreased when they are released. 
            When the reference count reaches 0, the message is destroyed.
            @returns The reference count on the message.
         */
        public int RefCount => m_refCount;

        /**
            Is this a block message?
            Block messages are of type BlockMessage and can have a data block attached to the message.
            @returns True if this is a block message, false otherwise.
            @see BlockMessage.
         */
        public bool IsBlockMessage => m_blockMessage;

        /**
            Virtual serialize function (read).
            Reads the message in from a bitstream.
            Don't override this method directly, instead, use the YOJIMBO_VIRTUAL_SERIALIZE_FUNCTIONS macro in your derived message class to redirect it to a templated serialize method.
            This way you can implement serialization for your packets in a single method and the C++ compiler takes care of generating specialized read, write and measure implementations for you. 
            See tests/shared.h for examples of this.
         */
        //public abstract bool SerializeInternal(ReadStream stream);

        /**
            Virtual serialize function (write).
            Write the message to a bitstream.
            Don't override this method directly, instead, use the YOJIMBO_VIRTUAL_SERIALIZE_FUNCTIONS macro in your derived message class to redirect it to a templated serialize method.
            This way you can implement serialization for your packets in a single method and the C++ compiler takes care of generating specialized read, write and measure implementations for you. 
            See tests/shared.h for examples of this.
         */
        //public abstract bool SerializeInternal(WriteStream stream);

        /**
            Virtual serialize function (measure).
            Measure how many bits this message would take to write. This is used when working out how many messages will fit within the channel packet budget.
            Don't override this method directly, instead, use the YOJIMBO_VIRTUAL_SERIALIZE_FUNCTIONS macro in your derived message class to redirect it to a templated serialize method.
            This way you can implement serialization for your packets in a single method and the C++ compiler takes care of generating specialized read, write and measure implementations for you. 
            See tests/shared.h for examples of this.
         */
        //public abstract bool SerializeInternal(MeasureStream stream);

        /**
            Add a reference to the message.
            This is called when a message is included in a packet and added to the receive queue. 
            This way we don't have to pass messages by value (more efficient) and messages get cleaned up when they are delivered and no packets refer to them.
         */
        protected internal void Acquire() { yojimbo.assert(m_refCount > 0); m_refCount++; }

        /**
            Remove a reference from the message.
            Message are deleted when the number of references reach zero. Messages have reference count of 1 after creation.
         */
        protected internal void Release() { yojimbo.assert(m_refCount > 0); m_refCount--; }

        /**
            Message destructor.
            @see MessageFactory::Release
         */
        public override void Dispose()
        {
            yojimbo.assert(m_refCount == 0);
        }

        int m_refCount;                             ///< Number of references on this message object. Starts at 1. Message is destroyed when it reaches 0.
        ushort m_id;                                ///< The message id. For messages sent over reliable-ordered channels, this starts at 0 and increases with each message sent. For unreliable-unordered channels this is set to the sequence number of the packet the message was included in.
        ushort m_type;                              ///< The message type. Corresponds to the type integer used when the message was created though the message factory.
        bool m_blockMessage;                        ///< 1 if this is a block message. 0 otherwise. If 1 then you can cast the Message* to BlockMessage*. Lightweight RTTI.
    }

    /**
        A message which can have a block of data attached to it.
        @see ChannelConfig
     */
    public class BlockMessage : Message
    {
        /**
            Block message constructor.
            Don't call this directly, use a message factory instead.
            @see MessageFactory::CreateMessage
         */
        public BlockMessage() : base(true)
        {
            m_allocator = null;
            m_blockData = null;
            m_blockSize = 0;
        }

        /**
            Attach a block to this message.
            You can only attach one block. This method will assert if a block is already attached.
            @see Client::AttachBlockToMessage
            @see Server::AttachBlockToMessage
         */
        public void AttachBlock(Allocator allocator, byte[] blockData, int blockSize)
        {
            yojimbo.assert(blockData != null);
            yojimbo.assert(blockSize > 0);
            yojimbo.assert(m_blockData == null);
            m_allocator = allocator;
            m_blockData = blockData;
            m_blockSize = blockSize;
        }

        /** 
            Detach the block from this message.
            By doing this you are responsible for copying the block pointer and allocator and making sure the block is freed.
            This could be used for example, if you wanted to copy off the block and store it somewhere, without the cost of copying it.
            @see Client::DetachBlockFromMessage
            @see Server::DetachBlockFromMessage
         */
        public void DetachBlock()
        {
            m_allocator = null;
            m_blockData = null;
            m_blockSize = 0;
        }

        /**
            Get the allocator used to allocate the block.
            @returns The allocator for the block. null if no block is attached to this message.
         */
        public Allocator Allocator =>
            m_allocator;

        /**
            Get the block data pointer.
            @returns The block data pointer. null if no block is attached.
         */
        public byte[] BlockData =>
            m_blockData;

        /**
            Get the size of the block attached to this message.
            @returns The size of the block (bytes). 0 if no block is attached.
         */
        public int BlockSize =>
            m_blockSize;

        ///**
        //    Templated serialize function for the block message. Doesn't do anything. The block data is serialized elsewhere.
        //    You can override the serialize methods on a block message to implement your own serialize function. It's just like a regular message with a block attached to it.
        //    @see ConnectionPacket
        //    @see ChannelPacketData
        //    @see ReliableOrderedChannel
        //    @see UnreliableUnorderedChannel
        // */
        //public bool Serialize(BaseStream stream) => true;

        /**
            If a block was attached to the message, it is freed here.
         */
        public override void Dispose()
        {
            if (m_allocator != null)
            {
                m_blockData = null;
                m_blockSize = 0;
                m_allocator = null;
            }
            base.Dispose();
        }

        Allocator m_allocator;                      ///< Allocator for the block attached to the message. null if no block is attached.
        byte[] m_blockData;                         ///< The block data. null if no block is attached.
        int m_blockSize;                            ///< The block size (bytes). 0 if no block is attached.
    }

    /**
        Message factory error level.
     */
    public enum MessageFactoryErrorLevel
    {
        MESSAGE_FACTORY_ERROR_NONE,                         ///< No error. All is well.
        MESSAGE_FACTORY_ERROR_FAILED_TO_ALLOCATE_MESSAGE,   ///< Failed to allocate a message. Typically this means we ran out of memory on the allocator backing the message factory.
    }

    /**
        Defines the set of message types that can be created.

        You can derive a message factory yourself to create your own message types, or you can use these helper macros to do it for you:
        
            YOJIMBO_MESSAGE_FACTORY_START
            YOJIMBO_DECLARE_MESSAGE_TYPE
            YOJIMBO_MESSAGE_FACTORY_FINISH
        
        See tests/shared.h for an example showing how to use the macros.
     */
    public class MessageFactory
    {
        /**
            Message factory allocator.
            Pass in the number of message types for the message factory from the derived class.
            @param allocator The allocator used to create messages.
            @param numTypes The number of message types. Valid types are in [0,numTypes-1].
         */
        public MessageFactory(Allocator allocator, int numTypes)
        {
            m_allocator = allocator;
            m_numTypes = numTypes;
            m_errorLevel = MessageFactoryErrorLevel.MESSAGE_FACTORY_ERROR_NONE;
        }

        /**
            Message factory destructor.
            Checks for message leaks if YOJIMBO_DEBUG_MESSAGE_LEAKS is defined and not equal to zero. This is on by default in debug build.
         */
        public virtual void Dispose()
        {
            yojimbo.assert(m_allocator != null);

            m_allocator = null;

#if YOJIMBO_DEBUG_MESSAGE_LEAKS
            // Reports and fails on any leaked message. Fails through the assert handler rather than exiting directly,
            // so programs embedding yojimbo (editors, tools) can intercept via yojimbo.set_assert_function.
            if (allocated_messages.Count != 0)
            {
                yojimbo.printf(yojimbo.LOG_LEVEL_ERROR, "you leaked messages!\n");
                yojimbo.printf(yojimbo.LOG_LEVEL_ERROR, $"{allocated_messages.Count} messages leaked\n");
                foreach (var i in allocated_messages)
                {
                    var message = i.Key;
                    yojimbo.printf(yojimbo.LOG_LEVEL_ERROR, $"leaked message {message} (type {message.Type}, refcount {message.RefCount})\n");
                }
                yojimbo.assert(false, "Message leaks detected, see log");
            }
#endif
        }

        /**
            Create a message by type.
            IMPORTANT: Check the message pointer returned by this call. It can be null if there is no memory to create a message!
            Messages returned from this function have one reference added to them. When you are finished with the message, pass it to MessageFactory::Release.
            @param type The message type in [0,numTypes-1].
            @returns The allocated message, or null if the message could not be allocated. If the message allocation fails, the message factory error level is set to MESSAGE_FACTORY_ERROR_FAILED_TO_ALLOCATE_MESSAGE.
            @see MessageFactory::AddRef
            @see MessageFactory::ReleaseMessage
         */
        public Message CreateMessage(int type)
        {
            yojimbo.assert(type >= 0);
            yojimbo.assert(type < m_numTypes);
            var message = CreateMessageInternal(type);
            if (message == null)
            {
                m_errorLevel = MessageFactoryErrorLevel.MESSAGE_FACTORY_ERROR_FAILED_TO_ALLOCATE_MESSAGE;
                return null;
            }
#if YOJIMBO_DEBUG_MESSAGE_LEAKS
            allocated_messages[message] = 1;
            yojimbo.assert(allocated_messages.ContainsKey(message));
#endif
            return message;
        }

        /**
            Add a reference to a message.
            @param message The message to add a reference to.
            @see MessageFactory::Create
            @see MessageFactory::Release
         */
        public void AcquireMessage(Message message)
        {
            yojimbo.assert(message != null);
            if (message != null)
                message.Acquire();
        }

        /**
            Remove a reference from a message.
            Messages have 1 reference when created. When the reference count reaches 0, they are destroyed.
            The caller's reference is always set to null: after releasing a message you no longer own it, whether or not other references keep it alive (C++ callers must never use the pointer after release either).
            @see MessageFactory::Create
            @see MessageFactory::AddRef
         */
        public void ReleaseMessage<TMessage>(ref TMessage message) where TMessage : Message
        {
            yojimbo.assert(message != null);
            if (message == null)
                return;
            ReleaseMessage(message);
            message = null;
        }

        /**
            Remove a reference from a message.
            Messages have 1 reference when created. When the reference count reaches 0, they are destroyed.
         */
        public void ReleaseMessage(Message message)
        {
            yojimbo.assert(message != null);
            if (message == null)
                return;
            message.Release();
            if (message.RefCount == 0)
            {
#if YOJIMBO_DEBUG_MESSAGE_LEAKS
                yojimbo.assert(allocated_messages.ContainsKey(message));
                allocated_messages.Remove(message);
#endif
                yojimbo.assert(m_allocator != null);
                message.Dispose();
            }
        }

        /**
            Get the number of message types supported by this message factory.
            @returns The number of message types.
         */
        public int NumTypes =>
            m_numTypes;

        /**
            Get the allocator used to create messages.
            @returns The allocator.
         */
        public Allocator Allocator
        {
            get
            {
                yojimbo.assert(m_allocator != null);
                return m_allocator;
            }
        }

        /**
            Get the error level.
            When used with a client or server, an error level on a message factory other than MESSAGE_FACTORY_ERROR_NONE triggers a client disconnect.
         */
        public MessageFactoryErrorLevel ErrorLevel =>
            m_errorLevel;

        /**
            Clear the error level back to no error.
         */
        public void ClearErrorLevel() =>
            m_errorLevel = MessageFactoryErrorLevel.MESSAGE_FACTORY_ERROR_NONE;

        /**
            This method is overridden to create messages by type.
            @param type The type of message to be created.
            @returns The message created. Its reference count is 1.
         */
        protected virtual Message CreateMessageInternal(int type) => null;

        /**
            Set the message type of a message.
            @param message The message object.
            @param type The message type to set.
         */
        protected void SetMessageType(Message message, int type) => message.Type = type;

#if YOJIMBO_DEBUG_MESSAGE_LEAKS
        Dictionary<Message, int> allocated_messages = new Dictionary<Message, int>();   ///< The set of allocated messages for this factory. Used to track down message leaks.
#endif
        Allocator m_allocator;                      ///< The allocator used to create messages.
        int m_numTypes;                             ///< The number of message types.
        MessageFactoryErrorLevel m_errorLevel;      ///< The message factory error level.
    }

    /** 
        Start a definition of a new message factory.
        This is a helper macro to make declaring your own message factory class easier.
        @param factory_class The name of the message factory class to generate.
        @param num_message_types The number of message types for this factory.
        See tests/shared.h for an example of usage.
     */
    //#define YOJIMBO_MESSAGE_FACTORY_START(factory_class, num_message_types)
    public class MESSAGE_FACTORY_START : MessageFactory
    {
        readonly Dictionary<int, Type> Types = new Dictionary<int, Type>();

        public MESSAGE_FACTORY_START(Allocator allocator, int num_message_types) : base(allocator, num_message_types) { }

        /** 
            Add a message type to a message factory.
            This is a helper macro to make declaring your own message factory class easier.
            @param message_type The message type value. This is typically an enum value.
            @param message_class The message class to instantiate when a message of this type is created.
            See tests/shared.h for an example of usage.
         */
        //#define YOJIMBO_DECLARE_MESSAGE_TYPE(message_type, message_class)
        public void DECLARE_MESSAGE_TYPE(int message_type, Type message_class) =>
            Types.Add(message_type, message_class);

        protected override Message CreateMessageInternal(int type)
        {
            if (!Types.TryGetValue(type, out var message_class))
                return null;
            var message = (Message)Activator.CreateInstance(message_class);
            if (message == null)
                return null;
            SetMessageType(message, type);
            return message;
        }

        /** 
        Finish the definition of a new message factory.
        This is a helper macro to make declaring your own message factory class easier.
        See tests/shared.h for an example of usage.
        */
        //#define YOJIMBO_MESSAGE_FACTORY_FINISH()
        public void MESSAGE_FACTORY_FINISH() { }
    }

    static partial class yojimbo
    {
        /**
            Helper function to serialize a block attached to a message. Used by channel implementations.
            Wire format: serialize_int( blockSize, 1, maxBlockSize ) then serialize_bytes( blockData, blockSize ).
         */
        public static bool SerializeMessageBlock(BaseStream stream, MessageFactory messageFactory, BlockMessage blockMessage, int maxBlockSize)
        {
            var blockSize = stream.IsWriting ? blockMessage.BlockSize : 0;

            if (!stream.serialize_int(ref blockSize, 1, maxBlockSize))
                return false;

            byte[] blockData;

            if (stream.IsReading)
            {
                var allocator = messageFactory.Allocator;
                blockData = new byte[blockSize];
                blockMessage.AttachBlock(allocator, blockData, blockSize);
            }
            else
                blockData = blockMessage.BlockData;

            if (!stream.serialize_bytes(blockData, blockSize))
                return false;

            return true;
        }
    }
}
