/*
    Cross-implementation interop test (C++ side).

    Built against the upstream library in cpp/. The C# side (interop/cs) speaks the same protocol, so any
    pairing of the two can be run:

        interop server [port]
        interop client [port]

    The server echoes every message it receives back to the sender on the same channel. The client sends
    NumMessages reliable-ordered messages (every 8th one a block message, some multi-fragment) plus a stream
    of unreliable messages, and checks that every reliable echo comes back in order with the right contents.

    Exit code 0 means the run passed. Both sides use the default ClientServerConfig, an all-zero private key
    and an insecure connect, so the connect token is generated by the client and decrypted by the server:
    a mixed pairing also checks that the two implementations agree on XChaCha20-Poly1305.
*/

#include "yojimbo.h"
#include "shared.h"
#include <signal.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>

using namespace yojimbo;

static const int NumMessages = 1000;
static const int BlockEvery = 8;
static const double TimeoutSeconds = 60.0;

static int BlockSizeFor( int sequence ) { return 1 + ( sequence * 977 ) % 5000; }

static uint8_t BlockByte( int sequence, int i ) { return (uint8_t) ( ( sequence * 31 + i * 7 ) & 0xFF ); }

static void InitConfig( ClientServerConfig & config )
{
    config.protocolId = ProtocolId;
    config.numChannels = 2;
    config.channel[0].type = CHANNEL_TYPE_RELIABLE_ORDERED;
    config.channel[1].type = CHANNEL_TYPE_UNRELIABLE_UNORDERED;
}

static int ServerMain( int port )
{
    ClientServerConfig config;
    InitConfig( config );

    uint8_t privateKey[KeyBytes];
    memset( privateKey, 0, KeyBytes );

    double time = 100.0;
    const double deltaTime = 0.01;

    Server server( GetDefaultAllocator(), privateKey, Address( "127.0.0.1", port ), config, adapter, time );
    if ( !server.Start( MaxClients ) )
    {
        printf( "server: failed to start\n" );
        return 1;
    }
    printf( "server: listening on 127.0.0.1:%d\n", port );
    fflush( stdout );

    bool hadClient = false;
    double idleSince = time;
    while ( true )
    {
        server.SendPackets();
        server.ReceivePackets();
        time += deltaTime;
        server.AdvanceTime( time );

        bool anyConnected = false;
        for ( int clientIndex = 0; clientIndex < MaxClients; ++clientIndex )
        {
            if ( !server.IsClientConnected( clientIndex ) )
                continue;
            anyConnected = true;
            hadClient = true;
            for ( int channel = 0; channel < config.numChannels; ++channel )
            {
                Message * message;
                while ( ( message = server.ReceiveMessage( clientIndex, channel ) ) != NULL )
                {
                    if ( !server.CanSendMessage( clientIndex, channel ) )
                    {
                        server.ReleaseMessage( clientIndex, message );
                        continue;
                    }
                    if ( message->GetType() == TEST_BLOCK_MESSAGE )
                    {
                        TestBlockMessage * in = (TestBlockMessage*) message;
                        TestBlockMessage * out = (TestBlockMessage*) server.CreateMessage( clientIndex, TEST_BLOCK_MESSAGE );
                        out->sequence = in->sequence;
                        uint8_t * block = server.AllocateBlock( clientIndex, in->GetBlockSize() );
                        memcpy( block, in->GetBlockData(), in->GetBlockSize() );
                        server.AttachBlockToMessage( clientIndex, out, block, in->GetBlockSize() );
                        server.SendMessage( clientIndex, channel, out );
                    }
                    else if ( message->GetType() == TEST_MESSAGE )
                    {
                        TestMessage * out = (TestMessage*) server.CreateMessage( clientIndex, TEST_MESSAGE );
                        out->sequence = ( (TestMessage*) message )->sequence;
                        server.SendMessage( clientIndex, channel, out );
                    }
                    server.ReleaseMessage( clientIndex, message );
                }
            }
        }

        // exit once the client has come and gone, or nobody shows up
        if ( anyConnected )
            idleSince = time;
        else if ( hadClient && time - idleSince > 1.0 )
            break;
        else if ( !hadClient && time - idleSince > TimeoutSeconds )
        {
            printf( "server: no client connected\n" );
            server.Stop();
            return 1;
        }

        yojimbo_sleep( deltaTime );
    }

    server.Stop();
    printf( "server: done\n" );
    return 0;
}

static int ClientMain( int port )
{
    ClientServerConfig config;
    InitConfig( config );

    uint8_t privateKey[KeyBytes];
    memset( privateKey, 0, KeyBytes );

    uint64_t clientId = 0;
    yojimbo_random_bytes( (uint8_t*) &clientId, 8 );

    double time = 100.0;
    const double deltaTime = 0.01;

    Client client( GetDefaultAllocator(), Address( "0.0.0.0" ), config, adapter, time );
    client.InsecureConnect( privateKey, clientId, Address( "127.0.0.1", port ) );

    int numSent = 0;
    int numReceived = 0;
    int numUnreliableEchoes = 0;
    uint16_t unreliableSequence = 0;
    const double start = time;
    int result = 1;

    while ( true )
    {
        client.SendPackets();
        client.ReceivePackets();
        time += deltaTime;
        client.AdvanceTime( time );

        if ( client.ConnectionFailed() || ( client.IsDisconnected() && time - start > 1.0 ) )
        {
            printf( "client: connection failed (%s)\n", GetClientDisconnectReasonString( client.GetDisconnectReason() ) );
            break;
        }

        if ( time - start > TimeoutSeconds )
        {
            printf( "client: timed out with %d/%d echoes\n", numReceived, NumMessages );
            break;
        }

        if ( client.IsConnected() )
        {
            while ( numSent < NumMessages && client.CanSendMessage( 0 ) )
            {
                if ( numSent % BlockEvery == 0 )
                {
                    TestBlockMessage * message = (TestBlockMessage*) client.CreateMessage( TEST_BLOCK_MESSAGE );
                    message->sequence = (uint16_t) numSent;
                    const int blockSize = BlockSizeFor( numSent );
                    uint8_t * block = client.AllocateBlock( blockSize );
                    for ( int i = 0; i < blockSize; ++i )
                        block[i] = BlockByte( numSent, i );
                    client.AttachBlockToMessage( message, block, blockSize );
                    client.SendMessage( 0, message );
                }
                else
                {
                    TestMessage * message = (TestMessage*) client.CreateMessage( TEST_MESSAGE );
                    message->sequence = (uint16_t) numSent;
                    client.SendMessage( 0, message );
                }
                numSent++;
            }

            if ( client.CanSendMessage( 1 ) )
            {
                TestMessage * message = (TestMessage*) client.CreateMessage( TEST_MESSAGE );
                message->sequence = unreliableSequence++;
                client.SendMessage( 1, message );
            }

            Message * message;
            while ( ( message = client.ReceiveMessage( 0 ) ) != NULL )
            {
                const int expected = numReceived;
                bool ok;
                if ( expected % BlockEvery == 0 )
                {
                    ok = message->GetType() == TEST_BLOCK_MESSAGE && ( (TestBlockMessage*) message )->sequence == (uint16_t) expected;
                    if ( ok )
                    {
                        TestBlockMessage * blockMessage = (TestBlockMessage*) message;
                        ok = blockMessage->GetBlockSize() == BlockSizeFor( expected );
                        for ( int i = 0; ok && i < blockMessage->GetBlockSize(); ++i )
                            ok = blockMessage->GetBlockData()[i] == BlockByte( expected, i );
                    }
                }
                else
                {
                    ok = message->GetType() == TEST_MESSAGE && ( (TestMessage*) message )->sequence == (uint16_t) expected;
                }
                client.ReleaseMessage( message );
                if ( !ok )
                {
                    printf( "client: echo %d is wrong\n", expected );
                    client.Disconnect();
                    return 1;
                }
                numReceived++;
            }

            while ( ( message = client.ReceiveMessage( 1 ) ) != NULL )
            {
                numUnreliableEchoes++;
                client.ReleaseMessage( message );
            }

            if ( numReceived == NumMessages )
            {
                printf( "client: %d reliable echoes verified (%d blocks), %d unreliable echoes\n", numReceived, ( NumMessages + BlockEvery - 1 ) / BlockEvery, numUnreliableEchoes );
                result = numUnreliableEchoes > 0 ? 0 : 1;
                if ( result )
                    printf( "client: no unreliable echoes\n" );
                break;
            }
        }

        yojimbo_sleep( deltaTime );
    }

    client.Disconnect();
    return result;
}

int main( int argc, char * argv[] )
{
    if ( argc < 2 || ( strcmp( argv[1], "server" ) != 0 && strcmp( argv[1], "client" ) != 0 ) )
    {
        printf( "usage: interop server|client [port]\n" );
        return 1;
    }

    const int port = argc >= 3 ? atoi( argv[2] ) : ServerPort;

    if ( !InitializeYojimbo() )
    {
        printf( "error: failed to initialize yojimbo\n" );
        return 1;
    }

    yojimbo_log_level( YOJIMBO_LOG_LEVEL_ERROR );

    srand( (unsigned int) time( NULL ) );

    const int result = strcmp( argv[1], "server" ) == 0 ? ServerMain( port ) : ClientMain( port );

    ShutdownYojimbo();

    printf( "%s\n", result == 0 ? "PASS" : "FAIL" );

    return result;
}
